axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.5
scale_linear_turbo: 2

axis_angular: 2  # Left thumb stick horizontal
scale_angular: 1

enable_button: 5  # Left trigger button
enable_turbo_button: 9  # Right trigger button
